#how to connect from qnas to remote convert worker

development:
  remote_host: 'xxxx'
  remote_port: 1000

test:
  remote_host: 'does not exists'
  remote_port: 1000

production:
  remote_host: '192.168.1.0'
  remote_port: 8999




