# converter is running on server PC, not on qnas, qnas connection is used as a backup

development:
  remote_port_converter: 8999
  remote_port_scanner: 8998
  remote_host: 'donald'

test:
  remote_port_converter: 8999
  remote_port_scanner: 8998
  remote_host: 'does not exists'


production:
  remote_port_converter: 8999
  remote_port_scanner: 8998
  remote_host: 'donald'



