# converter is running on server PC, not on qnas, qnas connection is used as a backup

development:
  remote_host: 'qnas'
  remote_port: 8999

test:
  remote_host: 'does not exists'
  remote_port: 8999

production:
  remote_host: 'remote'
  remote_port: 8999



