development:
  morphology: libstemmer_de
  enable_star: true
  port: 9312
production:
  morphology: libstemmer_de
  enable_star: true
  port: 9313
  bin_path: /opt/bin
  searchd_file_path: /share/Storage/sphinx_index




